steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/voteplus-kmajda/voteplus', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/voteplus-kmajda/voteplus']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'voteplus', '--image', 'gcr.io/voteplus-kmajda/voteplus', '--region', 'us-central1']
images:
- gcr.io/voteplus-kmajda/voteplus